FROM debian:buster

# RUN apk update && apk upgrade

# RUN apk add nginx

# RUN nginx -t

# RUN service nginx start

# COPY /Users/zmeribaa/Desktop/Inception/srcs/requirements/nginx/html /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
